name: skygen_ai
description: SkyGen AI Image Generator and Chat Assistant
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_markdown: ^0.6.14
  permission_handler: ^11.3.0

flutter:
  uses-material-design: true
  assets:
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
