name: skygen_ai
description: SkyGen AI - Advanced AI Assistant & Generator
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Networking & Async
  http: ^1.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  
  # UI & Assets
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_markdown: ^0.6.14
  flutter_highlight: ^0.7.0
  shimmer: ^3.0.0
  
  # Media Playback
  audioplayers: ^6.0.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  
  # Utils
  intl: ^0.19.0
  markdown: ^7.1.1
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true
