name: skygen_ai
description: SkyGen AI Image Generator
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Networking
  http: ^1.1.0
  # Local Storage & Paths
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  # State Management
  provider: ^6.1.1
  # Utilities
  uuid: ^4.3.3
  intl: ^0.19.0 # For timestamp formatting

flutter:
  uses-material-design: true
