name: skygen_ai
description: SkyGen AI Professional Assistant
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_markdown: ^0.6.14
  permission_handler: ^11.3.0
  flutter_highlight: ^0.7.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  markdown: ^7.1.1
  shimmer: ^3.0.0
  audioplayers: ^6.0.0
  url_launcher: ^6.2.5
  video_player: ^2.8.2
  chewie: ^1.7.5
  flutter_animate: ^4.5.0
  path: ^1.9.0

flutter:
  uses-material-design: true
